### ISSUE TITLE
0.8.0 is broken (missing file?)

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-config-wikimedia#99] opened 2018-09-09 17:29 UTC
Doesn't seem to like that we aren't including an .eslintrc.json file anymore...

```
Running "eslint:main" (eslint) task
Warning: Cannot read config file: /var/www/MediaWiki/extensions/VisualEditor/lib/ve/node_modules/eslint-config-wikimedia/.eslintrc.json
Error: ENOENT: no such file or directory, open '/var/www/MediaWiki/extensions/VisualEditor/lib/ve/node_modules/eslint-config-wikimedia/.eslintrc.json'
Referenced from: /var/www/MediaWiki/extensions/VisualEditor/lib/ve/node_modules/eslint-config-wikimedia/qunit.json
Referenced from: /var/www/MediaWiki/extensions/VisualEditor/lib/ve/tests/.eslintrc.json Use --force to continue.
```

**Comment by edg2s** [comment] 2018-09-09 17:30
This is precisely the issue I raised here: https://github.com/wikimedia/eslint-config-wikimedia/pull/95#pullrequestreview-147394192

**Comment by Krinkle** [comment] 2018-09-09 18:12
@edg2s The issue you're describing was meant to be fixed by the use of `"main": "wikimedia.json"` in package.json. I'll dig into why this is happening within ESLint...

This dot-file is only meant to apply to local development in this repository.

**Comment by Krinkle** [comment] 2018-09-09 18:12
The wikimedia config appears to work fine in my local testing.  But I can reproduce issue #99 in VisualEditor. Thanks for the stacktrace at #99, this actually reveals the problem:

```
Running "eslint:main" (eslint) task
[..]
Error: ENOENT: no such file or directory, open '..ve/node_modules/eslint-config-wikimedia/.eslintrc.json'
Referenced from: ..ve/node_modules/eslint-config-wikimedia/qunit.json
Referenced from: ..ve/tests/.eslintrc.json
[..]
```
The problem is with `qunit.json`, which we forgot to update the point to `wikimedia.json`. @edg2s 
 Could you update the pull request to update that qunit.json instead?

**Comment by Krinkle** [comment] 2018-09-09 18:13
The wikimedia config appears to work fine in my local testing.  But I can reproduce the issue in VisualEditor. Thanks for the stacktrace, it actually reveals the problem:

```
Running "eslint:main" (eslint) task
[..]
Error: ENOENT: no such file or directory, open '..ve/node_modules/eslint-config-wikimedia/.eslintrc.json'
Referenced from: ..ve/node_modules/eslint-config-wikimedia/qunit.json
Referenced from: ..ve/tests/.eslintrc.json
[..]
```
The problem is with `qunit.json`, which we forgot to update the point to `wikimedia.json`.

@edg2s Could you update the pull request to update qunit.json instead?

**Comment by edg2s** [comment] 2018-09-09 20:46
Fixed

**Closed as completed** 2018-09-09 21:25 UTC
Labels: Type: Problem
